[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "sphinx-latex-render"
version = "0.2.0"
description = "A Sphinx extension to render latex even in md compatible with markdown preview enhanced for vscode"
readme = "README.md"
requires-python = ">= 3.9"
license = "MIT"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
dependencies = [
    "sphinx",
]

[project.urls]
Repository = "https://github.com/fs570714/sphinx-latex-render"
"Bug Tracker" = "https://github.com/fs570714/sphinx-latex-render/issues"

[tool.setuptools.packages.find]
exclude = ["test*"]

[tool.coverage.run]
source = ["./"]
patch = "subprocess"